ffv.o: ffv.C ffv.h /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
ffv_Initialize.o: ffv_Initialize.C ffv.h \
 /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
ffv_Alloc.o: ffv_Alloc.C ffv.h /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
ffv_SetBC.o: ffv_SetBC.C ffv_SetBC.h ../FB/SetBC.h \
 /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/BndOuter.h \
 ../FB/Control.h ../FB/Medium.h ../FB/Component.h ../FB/FBUtility.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Intrinsic.h ffv_Define.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h \
 ../IP/IP_Define.h
ffv_Restart.o: ffv_Restart.C ffv.h \
 /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
ffv_Loop.o: ffv_Loop.C ffv.h /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
ffv_LS.o: ffv_LS.C ffv.h /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
ffv_Post.o: ffv_Post.C ffv.h /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
ffv_Heat.o: ffv_Heat.C ffv.h /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h ../FB/FindexS3D.h \
 ../FB/FindexS3D.h
ffv_Filter.o: ffv_Filter.C ffv.h /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
ffv_TerminateCtrl.o: ffv_TerminateCtrl.C \
 /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ffv_TerminateCtrl.h
NS_FS_E_Binary.o: NS_FS_E_Binary.C ffv.h \
 /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
NS_FS_E_CDS.o: NS_FS_E_CDS.C ffv.h \
 /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
PS_Binary.o: PS_Binary.C ffv.h /usr/local/FFV/CPMlib/include/cpm_ParaManager.h \
 /usr/local/FFV/CPMlib/include/cpm_Base.h \
 /usr/local/FFV/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/FFV/CPMlib/include/cpm_Version.h \
 /usr/local/FFV/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/FFV/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/FFV/CPMlib/include/cpm_ObjList.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/FFV/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h \
 ../FB/DomainInfo.h ../FB/FB_Define.h ../FB/mydebug.h ../FB/FBUtility.h \
 ../FB/Medium.h ../FB/Control.h ../FB/Component.h ../FB/BndOuter.h \
 ../FB/CompoFraction.h ../FB/Vec3.h ../FB/IterationControl.h \
 /usr/local/FFV/TextParser/include/TextParser.h \
 /usr/local/FFV/TextParser/include/TextParserCommon.h \
 /usr/local/FFV/TextParser/include/tpVersion.h ../FB/IntervalManager.h \
 ../FB/Alloc.h ../FB/FileIO.h ../FB/FB_Ffunc.h ../FB/ParseBC.h ../FB/Intrinsic.h \
 ../FB/ParseMat.h ../FB/VoxInfo.h ../FB/SetBC.h ../FB/History.h ../FB/Monitor.h \
 ../FB/MonCompo.h ../FB/basic_func.h ../FB/Sampling.h ffv_Version.h ffv_Define.h \
 ffv_SetBC.h ../F_CORE/ffv_Ffunc.h ../IP/IP_Jet.h ../IP/IP_Define.h \
 ../F_CORE/ffv_Ffunc.h ffv_TerminateCtrl.h ../FB/Glyph.h ../IP/IP_Duct.h \
 ../IP/IP_PPLT2D.h ../IP/IP_PMT.h ../IP/IP_Rect.h ../IP/IP_Step.h \
 ../IP/IP_Cylinder.h ../IP/IP_Polygon.h ../IP/IP_Sphere.h \
 /usr/local/FFV/PMlib/include/PerfMonitor.h \
 /usr/local/FFV/PMlib/include/PerfWatch.h \
 /usr/local/FFV/PMlib/include/pmVersion.h \
 /usr/local/FFV/Polylib/include/Polylib.h \
 /usr/local/FFV/Polylib/include/polygons/Polygons.h \
 /usr/local/FFV/Polylib/include/common/PolylibStat.h \
 /usr/local/FFV/Polylib/include/common/PolylibCommon.h \
 /usr/local/FFV/Polylib/include/common/PolylibDefine.h \
 /usr/local/FFV/Polylib/include/common/Vec3.h \
 /usr/local/FFV/Polylib/include/polygons/TriMesh.h \
 /usr/local/FFV/Polylib/include/common/BBox.h \
 /usr/local/FFV/Polylib/include/common/Vec2.h \
 /usr/local/FFV/Polylib/include/polygons/Triangle.h \
 /usr/local/FFV/Polylib/include/polygons/Vertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexTriangle.h \
 /usr/local/FFV/Polylib/include/polygons/PrivateTriangle.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroup.h \
 /usr/local/FFV/Polylib/include/groups/PolygonGroupFactory.h \
 /usr/local/FFV/Polylib/include/polyVersion.h \
 /usr/local/FFV/Polylib/include/MPIPolylib.h \
 /usr/local/FFV/Polylib/include/polygons/DVertex.h \
 /usr/local/FFV/Polylib/include/polygons/DVertexManager.h \
 /usr/local/FFV/Polylib/include/file_io/TriMeshIO.h \
 /usr/local/FFV/Polylib/include/file_io/stl.h \
 /usr/local/FFV/Polylib/include/polygons/VertexList.h \
 /usr/local/FFV/Polylib/include/file_io/obj.h \
 /usr/local/FFV/Polylib/include/common/tt.h \
 /usr/local/FFV/Polylib/include/file_io/vtk.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/RepairPolygonData/RepairPolygonData.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfoArray.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutInfo.h \
 /usr/local/FFV/Cutlib/include/CutInfo/CutNormalArray.h \
 /usr/local/FFV/Cutlib/include/Cutlib.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/GridAccessor.h \
 /usr/local/FFV/Cutlib/include/Version.h \
 /usr/local/FFV/Cutlib/include/GridAccessor/Cell.h \
 /usr/local/FFV/CIOlib/include/cio_DFI.h \
 /usr/local/FFV/CIOlib/include/cio_Define.h \
 /usr/local/FFV/CIOlib/include/cio_Version.h \
 /usr/local/FFV/CIOlib/include/cio_PathUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TextParser.h \
 /usr/local/FFV/CIOlib/include/cio_ActiveSubDomain.h \
 /usr/local/FFV/CIOlib/include/cio_endianUtil.h \
 /usr/local/FFV/CIOlib/include/cio_TypeArray.h \
 /usr/local/FFV/CIOlib/include/cio_Array.h \
 /usr/local/FFV/CIOlib/include/inline/cio_Array_inline.h \
 /usr/local/FFV/CIOlib/include/cio_FileInfo.h \
 /usr/local/FFV/CIOlib/include/cio_FilePath.h \
 /usr/local/FFV/CIOlib/include/cio_Unit.h \
 /usr/local/FFV/CIOlib/include/cio_TimeSlice.h \
 /usr/local/FFV/CIOlib/include/cio_Domain.h \
 /usr/local/FFV/CIOlib/include/cio_MPI.h \
 /usr/local/FFV/CIOlib/include/cio_Process.h \
 /usr/local/FFV/CIOlib/include/inline/cio_DFI_inline.h
