main.o: main.C comb.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/PMlib/include/PerfMonitor.h /usr/local/PMlib/include/PerfWatch.h \
 /usr/local/PMlib/include/Version.h /usr/local/CPMlib/include/cpm_ParaManager.h \
 /usr/local/CPMlib/include/cpm_Base.h /usr/local/CPMlib/include/cpm_Define.h \
 /usr/local/CPMlib/include/cpm_Version.h \
 /usr/local/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/CPMlib/include/cpm_ObjList.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h ../FB/FB_Define.h \
 ../FB/mydebug.h ../FB/FBUtility.h ../FB/TPControl.h \
 /usr/local/TextParser/include/TextParser.h \
 /usr/local/TextParser/include/TextParserCommon.h \
 /usr/local/TextParser/include/Version.h ../FB/dfi.h ../PLOT3D/PLOT3D_read.h \
 ../PLOT3D/PLOT3D.h ../FB/DomainInfo.h ../FB/FB_Ffunc.h ../PLOT3D/PLOT3D_write.h \
 FileIO_sph.h endianUtil.h ../FB/dfiinfo.h COMB_Define.h
comb.o: comb.C comb.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/PMlib/include/PerfMonitor.h /usr/local/PMlib/include/PerfWatch.h \
 /usr/local/PMlib/include/Version.h /usr/local/CPMlib/include/cpm_ParaManager.h \
 /usr/local/CPMlib/include/cpm_Base.h /usr/local/CPMlib/include/cpm_Define.h \
 /usr/local/CPMlib/include/cpm_Version.h \
 /usr/local/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/CPMlib/include/cpm_ObjList.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h ../FB/FB_Define.h \
 ../FB/mydebug.h ../FB/FBUtility.h ../FB/TPControl.h \
 /usr/local/TextParser/include/TextParser.h \
 /usr/local/TextParser/include/TextParserCommon.h \
 /usr/local/TextParser/include/Version.h ../FB/dfi.h ../PLOT3D/PLOT3D_read.h \
 ../PLOT3D/PLOT3D.h ../FB/DomainInfo.h ../FB/FB_Ffunc.h ../PLOT3D/PLOT3D_write.h \
 FileIO_sph.h endianUtil.h ../FB/dfiinfo.h COMB_Define.h
comb_sph.o: comb_sph.C comb.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/PMlib/include/PerfMonitor.h /usr/local/PMlib/include/PerfWatch.h \
 /usr/local/PMlib/include/Version.h /usr/local/CPMlib/include/cpm_ParaManager.h \
 /usr/local/CPMlib/include/cpm_Base.h /usr/local/CPMlib/include/cpm_Define.h \
 /usr/local/CPMlib/include/cpm_Version.h \
 /usr/local/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/CPMlib/include/cpm_ObjList.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h ../FB/FB_Define.h \
 ../FB/mydebug.h ../FB/FBUtility.h ../FB/TPControl.h \
 /usr/local/TextParser/include/TextParser.h \
 /usr/local/TextParser/include/TextParserCommon.h \
 /usr/local/TextParser/include/Version.h ../FB/dfi.h ../PLOT3D/PLOT3D_read.h \
 ../PLOT3D/PLOT3D.h ../FB/DomainInfo.h ../FB/FB_Ffunc.h ../PLOT3D/PLOT3D_write.h \
 FileIO_sph.h endianUtil.h ../FB/dfiinfo.h COMB_Define.h
comb_plot3d.o: comb_plot3d.C comb.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/PMlib/include/PerfMonitor.h /usr/local/PMlib/include/PerfWatch.h \
 /usr/local/PMlib/include/Version.h /usr/local/CPMlib/include/cpm_ParaManager.h \
 /usr/local/CPMlib/include/cpm_Base.h /usr/local/CPMlib/include/cpm_Define.h \
 /usr/local/CPMlib/include/cpm_Version.h \
 /usr/local/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/CPMlib/include/cpm_ObjList.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h ../FB/FB_Define.h \
 ../FB/mydebug.h ../FB/FBUtility.h ../FB/TPControl.h \
 /usr/local/TextParser/include/TextParser.h \
 /usr/local/TextParser/include/TextParserCommon.h \
 /usr/local/TextParser/include/Version.h ../FB/dfi.h ../PLOT3D/PLOT3D_read.h \
 ../PLOT3D/PLOT3D.h ../FB/DomainInfo.h ../FB/FB_Ffunc.h ../PLOT3D/PLOT3D_write.h \
 FileIO_sph.h endianUtil.h ../FB/dfiinfo.h COMB_Define.h
FileIO_sph.o: FileIO_sph.C FileIO_sph.h endianUtil.h ../FB/FB_Define.h \
 ../FB/mydebug.h
FileIO_read_sph.o: FileIO_read_sph.C FileIO_sph.h endianUtil.h ../FB/FB_Define.h \
 ../FB/mydebug.h
