dfi.o: dfi.C dfi.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h ../FB/FB_Define.h \
 ../FB/mydebug.h ../FB/util_Path.h
PLOT3D.o: PLOT3D.C PLOT3D.h /usr/local/CPMlib/include/cpm_Define.h \
 /opt/openmpi/include/mpi.h /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/CPMlib/include/cpm_ParaManager.h /usr/local/CPMlib/include/cpm_Base.h \
 /usr/local/CPMlib/include/cpm_Version.h \
 /usr/local/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/CPMlib/include/cpm_ObjList.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h ../FB/DomainInfo.h \
 ../FB/FB_Define.h ../FB/mydebug.h ../FB/FB_Ffunc.h
PLOT3D_read.o: PLOT3D_read.C PLOT3D_read.h PLOT3D.h \
 /usr/local/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/CPMlib/include/cpm_ParaManager.h /usr/local/CPMlib/include/cpm_Base.h \
 /usr/local/CPMlib/include/cpm_Version.h \
 /usr/local/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/CPMlib/include/cpm_ObjList.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h ../FB/DomainInfo.h \
 ../FB/FB_Define.h ../FB/mydebug.h ../FB/FB_Ffunc.h
PLOT3D_write.o: PLOT3D_write.C PLOT3D_write.h PLOT3D.h \
 /usr/local/CPMlib/include/cpm_Define.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h \
 /usr/local/CPMlib/include/cpm_ParaManager.h /usr/local/CPMlib/include/cpm_Base.h \
 /usr/local/CPMlib/include/cpm_Version.h \
 /usr/local/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/CPMlib/include/cpm_ObjList.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h ../FB/DomainInfo.h \
 ../FB/FB_Define.h ../FB/mydebug.h ../FB/FB_Ffunc.h
ffv_PLOT3D.o: ffv_PLOT3D.C ffv_PLOT3D.h dfi.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/mpi_portable_platform.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h /opt/openmpi/include/mpi.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/constants.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/exception.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/datatype_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/functions_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/request_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/comm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intracomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/topology_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/intercomm_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/group_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/op_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/errhandler_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h \
 /opt/openmpi/include/openmpi/ompi/mpi/cxx/file_inln.h ../FB/FB_Define.h \
 ../FB/mydebug.h ../FB/FB_Ffunc.h /usr/local/CPMlib/include/cpm_Define.h \
 ../FB/Control.h ../FB/DomainInfo.h /usr/local/CPMlib/include/cpm_ParaManager.h \
 /usr/local/CPMlib/include/cpm_Base.h /usr/local/CPMlib/include/cpm_Version.h \
 /usr/local/CPMlib/include/cpm_DomainInfo.h \
 /usr/local/CPMlib/include/cpm_EndianUtil.h \
 /usr/local/CPMlib/include/cpm_VoxelInfo.h \
 /usr/local/CPMlib/include/cpm_ObjList.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_inline.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndComm.h \
 /usr/local/CPMlib/include/inline/cpm_ParaManager_BndCommEx.h ../FB/Medium.h \
 ../FB/Component.h ../FB/FBUtility.h ../FB/BndOuter.h ../FB/Interval_Mngr.h \
 ../FB/CompoFraction.h ../FB/vec3.h ../FB/vec3_func.h ../FB/vec3f_func.h \
 ../FB/IterationControl.h /usr/local/TextParser/include/TextParser.h \
 /usr/local/TextParser/include/TextParserCommon.h \
 /usr/local/TextParser/include/Version.h ../F_CORE/ffv_Ffunc.h PLOT3D_write.h \
 PLOT3D.h PLOT3D_read.h
