#!/bin/bash
all:
	cd FFV && doxygen doxygen_FFV.conf
	cd FB && doxygen doxygen_FB.conf
	cd IP && doxygen doxygen_IP.conf
	cd PT && doxygen doxygen_PT.conf
	cd F_LS && doxygen doxygen_F_LS.conf
	cd FILE_IO && doxygen doxygen_FILE_IO.conf
