Cutlib.o: Cutlib.cpp ../include/Cutlib.h ../../Polylib_2_0_2/include/Polylib.h \
 ../../Polylib_2_0_2/include/polygons/Polygons.h \
 ../../Polylib_2_0_2/include/polygons/VTree.h \
 ../../Polylib_2_0_2/include/common/BBox.h \
 ../../Polylib_2_0_2/include/common/Vec2.h \
 ../../Polylib_2_0_2/include/common/Vec3.h \
 ../../Polylib_2_0_2/include/common/vec3_func.h \
 ../../Polylib_2_0_2/include/common/vec3f_func.h \
 ../../Polylib_2_0_2/include/common/axis.h \
 ../../Polylib_2_0_2/include/common/PolylibStat.h \
 ../../Polylib_2_0_2/include/common/PolylibCommon.h \
 ../../Polylib_2_0_2/include/common/tt.h \
 ../../Polylib_2_0_2/include/polygons/TriMesh.h \
 ../../Polylib_2_0_2/include/polygons/Triangle.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroup.h \
 /usr/include/libxml2/libxml/tree.h /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/dict.h /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/xmlmemory.h /usr/include/libxml2/libxml/threads.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroupFactory.h \
 ../../Polylib_2_0_2/include/file_io/PolylibConfig.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h CutlibCore.h \
 CutBoundary.h CutTriangle.h CutUtil.h
CutlibCore.o: CutlibCore.cpp CutlibCore.h ../include/Cutlib.h \
 ../../Polylib_2_0_2/include/Polylib.h \
 ../../Polylib_2_0_2/include/polygons/Polygons.h \
 ../../Polylib_2_0_2/include/polygons/VTree.h \
 ../../Polylib_2_0_2/include/common/BBox.h \
 ../../Polylib_2_0_2/include/common/Vec2.h \
 ../../Polylib_2_0_2/include/common/Vec3.h \
 ../../Polylib_2_0_2/include/common/vec3_func.h \
 ../../Polylib_2_0_2/include/common/vec3f_func.h \
 ../../Polylib_2_0_2/include/common/axis.h \
 ../../Polylib_2_0_2/include/common/PolylibStat.h \
 ../../Polylib_2_0_2/include/common/PolylibCommon.h \
 ../../Polylib_2_0_2/include/common/tt.h \
 ../../Polylib_2_0_2/include/polygons/TriMesh.h \
 ../../Polylib_2_0_2/include/polygons/Triangle.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroup.h \
 /usr/include/libxml2/libxml/tree.h /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/dict.h /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/xmlmemory.h /usr/include/libxml2/libxml/threads.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroupFactory.h \
 ../../Polylib_2_0_2/include/file_io/PolylibConfig.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h CutBoundary.h \
 CutTriangle.h CutUtil.h CutTiming.h
CutUtil.o: CutUtil.cpp CutUtil.h ../include/Cutlib.h \
 ../../Polylib_2_0_2/include/Polylib.h \
 ../../Polylib_2_0_2/include/polygons/Polygons.h \
 ../../Polylib_2_0_2/include/polygons/VTree.h \
 ../../Polylib_2_0_2/include/common/BBox.h \
 ../../Polylib_2_0_2/include/common/Vec2.h \
 ../../Polylib_2_0_2/include/common/Vec3.h \
 ../../Polylib_2_0_2/include/common/vec3_func.h \
 ../../Polylib_2_0_2/include/common/vec3f_func.h \
 ../../Polylib_2_0_2/include/common/axis.h \
 ../../Polylib_2_0_2/include/common/PolylibStat.h \
 ../../Polylib_2_0_2/include/common/PolylibCommon.h \
 ../../Polylib_2_0_2/include/common/tt.h \
 ../../Polylib_2_0_2/include/polygons/TriMesh.h \
 ../../Polylib_2_0_2/include/polygons/Triangle.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroup.h \
 /usr/include/libxml2/libxml/tree.h /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/dict.h /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/xmlmemory.h /usr/include/libxml2/libxml/threads.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroupFactory.h \
 ../../Polylib_2_0_2/include/file_io/PolylibConfig.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h
CutTriangle.o: CutTriangle.cpp CutTriangle.h ../include/Cutlib.h \
 ../../Polylib_2_0_2/include/Polylib.h \
 ../../Polylib_2_0_2/include/polygons/Polygons.h \
 ../../Polylib_2_0_2/include/polygons/VTree.h \
 ../../Polylib_2_0_2/include/common/BBox.h \
 ../../Polylib_2_0_2/include/common/Vec2.h \
 ../../Polylib_2_0_2/include/common/Vec3.h \
 ../../Polylib_2_0_2/include/common/vec3_func.h \
 ../../Polylib_2_0_2/include/common/vec3f_func.h \
 ../../Polylib_2_0_2/include/common/axis.h \
 ../../Polylib_2_0_2/include/common/PolylibStat.h \
 ../../Polylib_2_0_2/include/common/PolylibCommon.h \
 ../../Polylib_2_0_2/include/common/tt.h \
 ../../Polylib_2_0_2/include/polygons/TriMesh.h \
 ../../Polylib_2_0_2/include/polygons/Triangle.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroup.h \
 /usr/include/libxml2/libxml/tree.h /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/dict.h /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/xmlmemory.h /usr/include/libxml2/libxml/threads.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroupFactory.h \
 ../../Polylib_2_0_2/include/file_io/PolylibConfig.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h CutBoundary.h
CutBoundary.o: CutBoundary.cpp CutBoundary.h ../include/Cutlib.h \
 ../../Polylib_2_0_2/include/Polylib.h \
 ../../Polylib_2_0_2/include/polygons/Polygons.h \
 ../../Polylib_2_0_2/include/polygons/VTree.h \
 ../../Polylib_2_0_2/include/common/BBox.h \
 ../../Polylib_2_0_2/include/common/Vec2.h \
 ../../Polylib_2_0_2/include/common/Vec3.h \
 ../../Polylib_2_0_2/include/common/vec3_func.h \
 ../../Polylib_2_0_2/include/common/vec3f_func.h \
 ../../Polylib_2_0_2/include/common/axis.h \
 ../../Polylib_2_0_2/include/common/PolylibStat.h \
 ../../Polylib_2_0_2/include/common/PolylibCommon.h \
 ../../Polylib_2_0_2/include/common/tt.h \
 ../../Polylib_2_0_2/include/polygons/TriMesh.h \
 ../../Polylib_2_0_2/include/polygons/Triangle.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroup.h \
 /usr/include/libxml2/libxml/tree.h /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/dict.h /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/hash.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/xmlerror.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/libxml2/libxml/xmlmemory.h /usr/include/libxml2/libxml/threads.h \
 ../../Polylib_2_0_2/include/groups/PolygonGroupFactory.h \
 ../../Polylib_2_0_2/include/file_io/PolylibConfig.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h
