Cutlib.o: Cutlib.cpp ../include/Cutlib.h ../../Polylib-2.1/include/Polylib.h \
 ../../Polylib-2.1/include/polygons/Polygons.h \
 ../../Polylib-2.1/include/polygons/VTree.h \
 ../../Polylib-2.1/include/common/BBox.h ../../Polylib-2.1/include/common/Vec2.h \
 ../../Polylib-2.1/include/common/Vec3.h \
 ../../Polylib-2.1/include/common/vec3_func.h \
 ../../Polylib-2.1/include/common/vec3f_func.h \
 ../../Polylib-2.1/include/common/axis.h \
 ../../Polylib-2.1/include/common/PolylibStat.h \
 ../../Polylib-2.1/include/common/PolylibCommon.h \
 ../../Polylib-2.1/include/common/tt.h \
 ../../Polylib-2.1/include/polygons/TriMesh.h \
 ../../Polylib-2.1/include/polygons/Triangle.h \
 ../../Polylib-2.1/include/groups/PolygonGroup.h \
 /usr/local/textparser/include/TextParser.h \
 /usr/local/textparser/include/TextParserCommon.h \
 /usr/local/textparser/include/TextParserElement.h \
 /usr/local/textparser/include/TextParserTree.h \
 ../../Polylib-2.1/include/groups/PolygonGroupFactory.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h CutlibCore.h \
 CutBoundary.h CutTriangle.h CutUtil.h
CutlibCore.o: CutlibCore.cpp CutlibCore.h ../include/Cutlib.h \
 ../../Polylib-2.1/include/Polylib.h \
 ../../Polylib-2.1/include/polygons/Polygons.h \
 ../../Polylib-2.1/include/polygons/VTree.h \
 ../../Polylib-2.1/include/common/BBox.h ../../Polylib-2.1/include/common/Vec2.h \
 ../../Polylib-2.1/include/common/Vec3.h \
 ../../Polylib-2.1/include/common/vec3_func.h \
 ../../Polylib-2.1/include/common/vec3f_func.h \
 ../../Polylib-2.1/include/common/axis.h \
 ../../Polylib-2.1/include/common/PolylibStat.h \
 ../../Polylib-2.1/include/common/PolylibCommon.h \
 ../../Polylib-2.1/include/common/tt.h \
 ../../Polylib-2.1/include/polygons/TriMesh.h \
 ../../Polylib-2.1/include/polygons/Triangle.h \
 ../../Polylib-2.1/include/groups/PolygonGroup.h \
 /usr/local/textparser/include/TextParser.h \
 /usr/local/textparser/include/TextParserCommon.h \
 /usr/local/textparser/include/TextParserElement.h \
 /usr/local/textparser/include/TextParserTree.h \
 ../../Polylib-2.1/include/groups/PolygonGroupFactory.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h CutBoundary.h \
 CutTriangle.h CutUtil.h CutTiming.h
CutUtil.o: CutUtil.cpp CutUtil.h ../include/Cutlib.h \
 ../../Polylib-2.1/include/Polylib.h \
 ../../Polylib-2.1/include/polygons/Polygons.h \
 ../../Polylib-2.1/include/polygons/VTree.h \
 ../../Polylib-2.1/include/common/BBox.h ../../Polylib-2.1/include/common/Vec2.h \
 ../../Polylib-2.1/include/common/Vec3.h \
 ../../Polylib-2.1/include/common/vec3_func.h \
 ../../Polylib-2.1/include/common/vec3f_func.h \
 ../../Polylib-2.1/include/common/axis.h \
 ../../Polylib-2.1/include/common/PolylibStat.h \
 ../../Polylib-2.1/include/common/PolylibCommon.h \
 ../../Polylib-2.1/include/common/tt.h \
 ../../Polylib-2.1/include/polygons/TriMesh.h \
 ../../Polylib-2.1/include/polygons/Triangle.h \
 ../../Polylib-2.1/include/groups/PolygonGroup.h \
 /usr/local/textparser/include/TextParser.h \
 /usr/local/textparser/include/TextParserCommon.h \
 /usr/local/textparser/include/TextParserElement.h \
 /usr/local/textparser/include/TextParserTree.h \
 ../../Polylib-2.1/include/groups/PolygonGroupFactory.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h
CutTriangle.o: CutTriangle.cpp CutTriangle.h ../include/Cutlib.h \
 ../../Polylib-2.1/include/Polylib.h \
 ../../Polylib-2.1/include/polygons/Polygons.h \
 ../../Polylib-2.1/include/polygons/VTree.h \
 ../../Polylib-2.1/include/common/BBox.h ../../Polylib-2.1/include/common/Vec2.h \
 ../../Polylib-2.1/include/common/Vec3.h \
 ../../Polylib-2.1/include/common/vec3_func.h \
 ../../Polylib-2.1/include/common/vec3f_func.h \
 ../../Polylib-2.1/include/common/axis.h \
 ../../Polylib-2.1/include/common/PolylibStat.h \
 ../../Polylib-2.1/include/common/PolylibCommon.h \
 ../../Polylib-2.1/include/common/tt.h \
 ../../Polylib-2.1/include/polygons/TriMesh.h \
 ../../Polylib-2.1/include/polygons/Triangle.h \
 ../../Polylib-2.1/include/groups/PolygonGroup.h \
 /usr/local/textparser/include/TextParser.h \
 /usr/local/textparser/include/TextParserCommon.h \
 /usr/local/textparser/include/TextParserElement.h \
 /usr/local/textparser/include/TextParserTree.h \
 ../../Polylib-2.1/include/groups/PolygonGroupFactory.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h CutBoundary.h
CutBoundary.o: CutBoundary.cpp CutBoundary.h ../include/Cutlib.h \
 ../../Polylib-2.1/include/Polylib.h \
 ../../Polylib-2.1/include/polygons/Polygons.h \
 ../../Polylib-2.1/include/polygons/VTree.h \
 ../../Polylib-2.1/include/common/BBox.h ../../Polylib-2.1/include/common/Vec2.h \
 ../../Polylib-2.1/include/common/Vec3.h \
 ../../Polylib-2.1/include/common/vec3_func.h \
 ../../Polylib-2.1/include/common/vec3f_func.h \
 ../../Polylib-2.1/include/common/axis.h \
 ../../Polylib-2.1/include/common/PolylibStat.h \
 ../../Polylib-2.1/include/common/PolylibCommon.h \
 ../../Polylib-2.1/include/common/tt.h \
 ../../Polylib-2.1/include/polygons/TriMesh.h \
 ../../Polylib-2.1/include/polygons/Triangle.h \
 ../../Polylib-2.1/include/groups/PolygonGroup.h \
 /usr/local/textparser/include/TextParser.h \
 /usr/local/textparser/include/TextParserCommon.h \
 /usr/local/textparser/include/TextParserElement.h \
 /usr/local/textparser/include/TextParserTree.h \
 ../../Polylib-2.1/include/groups/PolygonGroupFactory.h \
 ../include/CutInfo/CutInfoArray.h ../include/CutInfo/CutInfo.h
